[package]
name = "rust-log-analyzer"
version = "0.1.0"
authors = ["Rust Project Developers"]
license = "MIT"

[dependencies]
brotli = "1.2"
clap = "2.31"
env_logger = "0.5"
failure = "0.1"
hyper = "0.11"
log = "0.4"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
